[build]
  publish = "build"
  command = "java -version && yarn crowdin:sync && yarn build"

[context.production]
  command = "yarn crowdin:sync && yarn build"

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 301