[build]
command = "yarn build"
publish = "build"

[[redirects]]
from = "/en/*"
to = "/:splat"

[[redirects]]
from = "/docs/getting-started/*"
to = "/docs/guides/getting-started/prerequisites"

[[redirects]]
from = "/docs/development/*"
to = "/docs/guides/getting-started/prerequisites"

[[redirects]]
from = "/docs/architecture/*"
to = "/docs/guides/getting-started/prerequisites"

[[redirects]]
from = "/docs/guides/*"
to = "/docs/guides/getting-started/prerequisites"

[[redirects]]
from = "/docs/debugging/*"
to = "/docs/guides/getting-started/prerequisites"

[[redirects]]
from = "/docs/testing/*"
to = "/docs/guides/getting-started/prerequisites"

[[redirects]]
from = "/docs/building/*"
to = "/docs/guides/getting-started/prerequisites"

[[redirects]]
from = "/docs/distribution/*"
to = "/docs/guides/getting-started/prerequisites"

[[redirects]]
from = "/docs/api/rust/*"
to = "https://docs.rs/tauri/1.0.0-rc.0/tauri/"

[[redirects]]
from = "/partners"
to = "/#sponsors"

[[redirects]]
from = "/benchmarks"
to = "/docs/about/benchmarks"
