name: "Bug Report 🐛"
description: Report an issue or a possible bug with the Tauri docs website.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "📝 Issue Description"
      description: Please describe the issue you are experiencing while using the Docs website.
      placeholder: Describe the problem you encountered in detail...
    validations:
      required: true
  - type: textarea
    id: page
    attributes:
      label: "📋 On which page(s) it occurs"
      description: Please indicate on which page(s) the issue occurs.
      placeholder: https://tauri.app/v1/guides/getting-started/setup
    validations:
        required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "🤔 Expected Behavior"
      description: Please describe what the expected behavior should be.
      placeholder: While scrolling, I expected... 
    validations:
      required: true
  - type: textarea
    id: current_behavior
    attributes:
      label: "🤨 Current Behavior"
      description: Please describe what the current behavior is.
      placeholder: But instead, on this page I'm noticing... 
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: 🖥️ Browser
      description: Indicate which browser and version you are using.
      placeholder: Chrome X
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "📄 Additional Information"
      description: Any additional information that may be relevant for the issue.
    validations:
      required: false
