# Copyright 2019-2024 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

blank_issues_enabled: true
contact_links:
  - name: 💬 Discord Chat
    url: https://discord.com/invite/tauri
    about: Ask questions and talk to other Tauri users and the maintainers
