name: 'Auto Assign'

on:
  pull_request:
 #   types: [opened]

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR to author
        env:
          GH_TOKEN: ${{ secrets.ORG_TAURI_BOT_PAT }}
        run: |
          gh api -X POST \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees" \
            -f assignees='["${{ github.event.pull_request.user.login }}"]'
