name: 'Auto Assign'

on:
  pull_request:
    types: [opened]

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR to author
        env:
          GH_TOKEN: ${{ secrets.ORG_TAURI_BOT_PAT }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          pr_author=${{ github.event.pull_request.user.login }}
          gh api -X POST \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/issues/${pr_number}/assignees" \
            -f assignees='["'${pr_author}'"]'
