name: build

on:
  push:
    branches:
      - feat/i18n-evergreen

jobs:
  build-locale-list:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      locale-list: ${{ steps.generate.outputs.locale-list }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - id: generate
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        run: |
          yarn
          yarn i18n:sync:dryrun
          node ./.scripts/ci-prebuild.js
      - uses: actions/upload-artifact@v3
        with:
          name: i18n
          path: i18n
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: config
          path: ./docusaurus.config.i18n.js
          if-no-files-found: error

  build-locales:
    needs: build-locale-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locale: ${{ fromJson(needs.build-locale-list.outputs.locale-list) }}
    steps:
      - uses: actions/checkout@v3
      - id: i18n
        uses: actions/download-artifact@v3
        with:
          name: i18n
      - id: config
        uses: actions/download-artifact@v3
        with:
          name: config
      - run: |
          tree -L 2 .
          cat ./docusaurus.config.i18n.js
          cat ./docusaurus.config.js
      - if: matrix.locale == 'en'
        env:
          LOCALE: ${{ matrix.locale }}
        run: |
          yarn
          yarn build --locale ${{ matrix.locale }} \
          --config ./docusaurus.config.i18n.js
      - if: matrix.locale != 'en'
        env:
          LOCALE: ${{ matrix.locale }}
        run: |
          yarn
          yarn build --locale ${{ matrix.locale }} \
          --config ./docusaurus.config.i18n.js \
          --out-dir ./build/${{ matrix.locale }}
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
