name: build

on:
  push:
    branches:
      - feat/i18n-evergreen

jobs:
  build-locale-list:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      locale-list: ${{ steps.generate.outputs.locale-list }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - id: generate
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        run: |
          yarn
          yarn i18n:sync:dryrun
          node ./.scripts/ci-prebuild.js
      - id: cache
        uses: actions/cache@v3
        with:
          path: i18n
          key: i18n

  build-locales:
    needs: build-locale-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locale: ${{ fromJson(needs.build-locale-list.outputs.locale-list) }}
    steps:
      - uses: actions/checkout@v3
      - id: cache
        uses: actions/cache@v3
        with:
          path: i18n
          key: i18n
      - name: Check for i18n folder
        if: steps.cache.outputs.cache-hit == 'false'
        run: exit 1
      - run: |
          yarn && yarn build --locale ${{ matrix.locale }}
      - uses: actions/cache@v3
        with:
          path: build
          key: ${{ matrix.locale }}-build
  merge-locales:
    needs: build-locales
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - env:
          LOCALES: ${{ needs.build-locale-list.outputs.locale-list }}
        run: |
          yarn
          node ./.scripts/ci-postbuild.js
