name: build

on:
  push:
    branches:
      - feat/i18n-evergreen

jobs:
  build-locale-list:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      locale-list: ${{ steps.generate.outputs.locale-list }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - id: generate
        env: 
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        run: |
          yarn
          yarn crowdin download
          node ./.scripts/generate-locales.js

  build-locale:
    needs: build-locale-list
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hour timeout
    strategy:
      matrix:
        locale: ${{ fromJson(needs.build-locale-list.outputs.locale-list) }}
    steps:
      - run: echo "This is locale ${{ matrix.locale }}"
