name: build

on:
  push:
    branches:
      - feat/i18n-evergreen
      
jobs:
  build-language-list:
    runs-on: ubuntu-latest
    outputs:
      language-list: LANGUAGE_LIST=$(node -e "let r=[]; for(let i = 1; i <= process.env.NUMBER_OF_JOBS; i++) { r.push(i) }; console.log(JSON.stringify(r));")

    steps:
      - run: |
          LANGUAGE_LIST=$(node -e "let r=[]; for(let i = 1; i <= process.env.NUMBER_OF_JOBS; i++) { r.push(i) }; console.log(JSON.stringify(r));")
          echo "::set-output name=build-language-list::$LANGUAGE_LIST"
