# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: build

on:
  workflow_dispatch:
  pull_request_target:
    branches: [dev]
  push:
    branches: [dev, next]

jobs:
  update-search-index:
    concurrency:
      group: search-indexing
      cancel-in-progress: true
    #needs: deploy-to-netlify
    #if: (github.event_name == 'push' && github.ref_name == 'dev')
    runs-on: ubuntu-latest
    env:
      MEILISEARCH_HOST_URL: https://ms-2b6734516304-1619.fra.meilisearch.io
      MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY_TEST }}
      CONFIG_FILE_PATH: ${{ github.workspace }}/scraper.json
    steps:
      - uses: actions/checkout@v3

      - name: Wait for Meilisearch
        run: node ./.scripts/wait-for-search.js

      - name: Run scraper
        run: |
          docker run -t --rm \
            -e MEILISEARCH_HOST_URL=$MEILISEARCH_HOST_URL \
            -e MEILISEARCH_API_KEY=$MEILISEARCH_API_KEY \
            -v $CONFIG_FILE_PATH:/docs-scraper/scraper.json \
            getmeili/docs-scraper:v0.12.7 pipenv run ./docs_scraper ./scraper.json

      - name: Wait for Meilisearch
        run: node ./.scripts/wait-for-search.js

      - name: Swap index
        run: |
          curl -X POST "$MEILISEARCH_HOST_URL/swap-indexes" -H "Authorization: Bearer $MEILISEARCH_API_KEY" -H "Content-Type: application/json" --data-binary "[ { "indexes": ["docs-v1-test", "docs-v1-staging"] } ]"
