name: Congrats

on:
  push:
    branches: [next]

jobs:
  congrats:
    uses: tauri-apps/automation/.github/workflows/congrats.yml@main
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      