name: i18n

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [i18n]
    
# Check if a branch exists
# If so, update it
# If not, create it from 'dev'
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check if branch exists
        id: branch-exists
        run: echo '::set-output name=BRANCH_EXISTS::git branch --list i18n'
      - name: Check result
        run: echo "Does the branch exist? ${{ steps.branch-exists.outputs.BRANCH_EXISTS }}"
