name: i18n

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: [i18n]

env:
  MAIN_BRANCH: dev
  I18N_BRANCH: i18ntest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check if branch exists
        id: branch-exists
        run: echo "::set-output name=BRANCHES::$(git branch --list $I18N_BRANCH)"
      - name: Create new branch
        if: ${{ steps.branch-exists.outputs.BRANCHES == ''}}
        run: git branch $I18N_BRANCH
      - name: Update branch
        if: ${{ steps.branch-exists.outputs.BRANCHES != ''}}
        run: |
          git checkout $I18N_BRANCH
          git merge $MAIN_BRANCH
      - name: Call workflow
        uses: ./.github/workflows/build.yml
