name: i18n-preview

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: [i18n-development]

env:
  MAIN_BRANCH: origin/dev
  I18N_BRANCH: i18n-preview

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Check if branch exists
        id: branch-exists
        run: echo "::set-output name=BRANCHES::$(git branch --list $I18N_BRANCH)"
      - name: Create new branch
        if: ${{ steps.branch-exists.outputs.BRANCHES == ''}}
        run: |
          git branch $I18N_BRANCH $MAIN_BRANCH
          git checkout $I18N_BRANCH
      - name: Update branch
        if: ${{ steps.branch-exists.outputs.BRANCHES != ''}}
        run: |
          git checkout $I18N_BRANCH
          git merge $MAIN_BRANCH
      - name: Update config
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        run: |
          yarn
          node ./.scripts/i18n-preview.js
      - name: Push branch
        run: |
          git config --global user.name 'Tauri Bot'
          git config --global user.email 'tauri-bot@tauri.studio'
          git commit -a -m "Add locales to docusaurus.config.js"
          git push --set-upstream origin i18n-preview

  call-workflow:
    needs: build
    uses: ./.github/workflows/build.yml
    with:
      ref: i18n-preview
