name: i18n-preview

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: [i18n-development]

env:
  MAIN_BRANCH: origin/i18n-development
  I18N_BRANCH: i18n-preview

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Update config
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        run: |
          yarn
          node ./.scripts/i18n-preview.js
      - name: Configure git
        run: |
          git config --global user.name 'Tauri Bot'
          git config --global user.email 'tauri-bot@tauri.studio'
      - name: Create pull request
        # soft fork of https://github.com/peter-evans/create-pull-request for security purposes
        uses: tauri-apps/create-pull-request@v3
        with:
          title: I18N Preview
          branch: i18n-preview
          draft: true
          token: ${{ secrets.TAURI_BOT_PAT }}
          body: |
            **DO NOT MERGE**
            This is used to create an ever-green deploy preview for Crowdin translations


